version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: usermgmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      driver-class-name: org.postgresql.Driver
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/usermgmt
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123qwe

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
