spring:
  application:
    name: UserManagementService

  datasource:
    username: postgres
    password: 123qwe
#    url: jdbc:h2:mem:test
#    driverClassName: org.h2.Driver
#    url: jdbc:postgresql://db:5432/usermgmt
    url: jdbc:postgresql://localhost:5432/UserManagement
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: root
      password: 123qwe

  # Enable Flyway and point to your migrations folder
  flyway:
    enabled: true
    locations: classpath:db/migration


  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
